matrix:

dist: trusty
sudo: required

language:
  - cpp

compiler:
  - gcc

notifications:
  email: false # turn off notifications

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - cmake-data
      - cmake

before_install:
  # we may use '/scripts/install-deps-ubuntu.sh' but this shell script does not have -y
  - set -ev
  - sudo apt-get install -y xorg-dev libglu1-mesa-dev libgl1-mesa-glx libglew-dev libjsoncpp-dev libeigen3-dev python3

before_script:
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  - mkdir build
  - cd build
  - cmake ../src/

script:
  # Run your build commands next
  - make -j
