dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
before_install:
  - set -env
  # install OpenGL, for GLFW
  - sudo apt-get -qq update
  - sudo apt-get install xorg-dev libglu1-mesa-dev libgl1-mesa-glx libglew-dev libglfw3-dev libjsoncpp-dev libeigen3-dev
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
script:
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  # Run your build commands next
  - mkdir build
  - cd build
  - cmake ../src/
  - make -j
