dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
  - clang
notifications:
  email: false # turn off notifications
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - cmake
before_install:
  - set -ev
  - sudo apt-get install -y xorg-dev libglu1-mesa-dev libgl1-mesa-glx libglew-dev libjsoncpp-dev libeigen3-dev
script:
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version

  # Run your build commands next
  #- ./scripts/install-deps-ubuntu.sh # this shell script does not have -y
  - mkdir build
  - cd build
  - cmake ../src/
  - make
